### ISSUE TITLE
ERR command 'debugLauncher.auto' not found

### ISSUE THREAD

**Issue by b-ozcan** [fabiospampinato/vscode-statusbar-debugger#12]
Hi,
Since the last update (yesterday) the debugger won't start if I click on it directly. Starting debugger from original VS Code button does work and the buttons of your pluging ("step over, into, out, restart, stop") do work too. 

**Error log:**
```
[Extension Host] WARNING: Promise with no error callback:16
log.ts:171   ERR command 'debugLauncher.auto' not found: Error: command 'debugLauncher.auto' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3030:36)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3029:885
    at n.Class.derive._oncancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:167:366)
    at t.executeCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3029:859)
    at e.$executeCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3194:579)
    at t._doInvokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3267:118)
    at t._invokeHandler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3266:742)
    at t._receiveRequest (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3265:322)
    at t._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3264:234)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3262:81
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:181:218)
    at a (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:318:348)
    at Socket.n._socketDataListener (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:318:567)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
console.ts:136 [Extension Host]% {exception: null, error: {…}, promise: {…}, id: 16}
```

**Comment by fabiospampinato** [comment]
Fixed in v2.0.1.

You should also install [Debug Launcher](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-debug-launcher) used in combination with StatusBar Debugger you can debug single files with a click.
